# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # npm run build
      - name: Install
        run: npm install

      - name: Build
        run: npm run tsc

      # 打包上传
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.ASSESS_TOKEN }}
          REMOTE_USER: "root"
          REMOTE_HOST: "81.69.12.254"
          SOURCE: ""
          TARGET: "/www/wwwroot/egg"

